// SPDX-License-Identifier: Apache-2.0
package tor

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
)

// torRole selects the torrc profile. The desktop hosts a single-hop onion
// service with no SOCKS listener; the client profile only exists for tests
// that need a second Tor dialing that service.
type torRole int

const (
	roleService torRole = iota
	roleClient
)

type torrcOptions struct {
	role            torRole
	dataDir         string
	controlPortFile string
	cookieFile      string
	ownerPID        int
	geoIP           string
	geoIPv6         string
}

// renderTorrc builds the generated torrc. The network starts disabled so the
// controller can take ownership, subscribe to events and register the onion
// before Tor makes any connection.
func renderTorrc(options torrcOptions) ([]byte, error) {
	if options.ownerPID <= 0 {
		return nil, errors.New("torrc needs the owning controller pid")
	}
	quoted := map[string]string{}
	for name, value := range map[string]string{
		"DataDirectory":          options.dataDir,
		"ControlPortWriteToFile": options.controlPortFile,
		"CookieAuthFile":         options.cookieFile,
		"GeoIPFile":              options.geoIP,
		"GeoIPv6File":            options.geoIPv6,
	} {
		if value == "" {
			continue
		}
		if !filepath.IsAbs(value) {
			return nil, fmt.Errorf("torrc %s must be absolute", name)
		}
		text, err := torQuote(value)
		if err != nil {
			return nil, fmt.Errorf("torrc %s: %w", name, err)
		}
		quoted[name] = text
	}
	for _, required := range []string{"DataDirectory", "ControlPortWriteToFile", "CookieAuthFile"} {
		if quoted[required] == "" {
			return nil, fmt.Errorf("torrc %s is required", required)
		}
	}
	lines := []string{
		"# Generated by Cialai tunnel-core; local edits are overwritten.",
		"DataDirectory " + quoted["DataDirectory"],
		"DisableNetwork 1",
		"ControlPort auto",
		"ControlPortWriteToFile " + quoted["ControlPortWriteToFile"],
		"CookieAuthentication 1",
		"CookieAuthFile " + quoted["CookieAuthFile"],
		"__OwningControllerProcess " + strconv.Itoa(options.ownerPID),
		"Log notice stdout",
	}
	switch options.role {
	case roleService:
		lines = append(lines,
			"SocksPort 0",
			"HiddenServiceNonAnonymousMode 1",
			"HiddenServiceSingleHopMode 1",
		)
	case roleClient:
		lines = append(lines, "SocksPort auto")
	default:
		return nil, fmt.Errorf("unknown torrc role %d", options.role)
	}
	for _, name := range []string{"GeoIPFile", "GeoIPv6File"} {
		if quoted[name] != "" {
			lines = append(lines, name+" "+quoted[name])
		}
	}
	return []byte(strings.Join(lines, "\n") + "\n"), nil
}

// torQuote writes a torrc quoted string. Control characters are refused rather
// than escaped so that no path can smuggle another configuration line.
func torQuote(value string) (string, error) {
	for _, char := range value {
		if unicode.IsControl(char) {
			return "", errors.New("value contains a control character")
		}
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value) + `"`, nil
}

// bundleGeoIP finds the GeoIP files of a Tor Expert Bundle, laid out as
// <root>/tor/tor[.exe] beside <root>/data/geoip. Missing files are skipped;
// Tor only logs a notice without them.
func bundleGeoIP(executable string) (string, string) {
	root := filepath.Dir(filepath.Dir(executable))
	existing := func(name string) string {
		path := filepath.Join(root, "data", name)
		if info, err := os.Stat(path); err == nil && info.Mode().IsRegular() {
			return path
		}
		return ""
	}
	return existing("geoip"), existing("geoip6")
}
