// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

type torFiles struct {
	controlPort string
	dataDir     string
	geoIP       string
	geoIPv6     string
	torrc       string
}

func makeTorFiles(state, bundleRoot, role string) (torFiles, error) {
	if state == "" {
		return torFiles{}, fmt.Errorf("state directory is required")
	}
	absoluteState, err := filepath.Abs(state)
	if err != nil {
		return torFiles{}, fmt.Errorf("resolve state directory: %w", err)
	}
	if err := os.MkdirAll(absoluteState, 0o700); err != nil {
		return torFiles{}, fmt.Errorf("create state directory: %w", err)
	}
	files := torFiles{
		controlPort: filepath.Join(absoluteState, "control-port"),
		dataDir:     filepath.Join(absoluteState, "tor-data"),
		geoIP:       filepath.Join(bundleRoot, "data", "geoip"),
		geoIPv6:     filepath.Join(bundleRoot, "data", "geoip6"),
		torrc:       filepath.Join(absoluteState, "torrc"),
	}
	if err := writeTorrc(files, role, os.Getpid()); err != nil {
		return torFiles{}, err
	}
	return files, nil
}

func writeTorrc(files torFiles, role string, ownerPID int) error {
	lines := []string{
		"# Generated by Cialai torpath; local edits are overwritten.",
		"ControlPort auto",
		"ControlPortWriteToFile " + torQuote(files.controlPort),
		"CookieAuthentication 1",
		"__OwningControllerProcess " + strconv.Itoa(ownerPID),
	}
	switch role {
	case "server":
		lines = append(lines,
			"SocksPort 0",
			"HiddenServiceNonAnonymousMode 1",
			"HiddenServiceSingleHopMode 1",
		)
	case "client":
		// bine supplies `SocksPort auto` on the command line and discovers it
		// through GETINFO, so no fixed local port is exposed here.
	default:
		return fmt.Errorf("unknown torrc role %q", role)
	}
	if files.geoIP != "" {
		lines = append(lines, "GeoIPFile "+torQuote(files.geoIP))
	}
	if files.geoIPv6 != "" {
		lines = append(lines, "GeoIPv6File "+torQuote(files.geoIPv6))
	}
	contents := []byte(strings.Join(lines, "\n") + "\n")
	temporary, err := os.CreateTemp(filepath.Dir(files.torrc), ".torrc-*")
	if err != nil {
		return fmt.Errorf("create torrc: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("chmod torrc: %w", err)
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write torrc: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("sync torrc: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close torrc: %w", err)
	}
	if runtime.GOOS == "windows" {
		if err := os.Remove(files.torrc); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("replace torrc: %w", err)
		}
	}
	if err := os.Rename(temporaryPath, files.torrc); err != nil {
		return fmt.Errorf("install torrc: %w", err)
	}
	return nil
}

func torQuote(value string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value) + `"`
}

func torBundleRoot(executable string) (string, error) {
	absolute, err := filepath.Abs(executable)
	if err != nil {
		return "", fmt.Errorf("resolve Tor executable: %w", err)
	}
	if info, err := os.Stat(absolute); err != nil {
		return "", fmt.Errorf("stat Tor executable: %w", err)
	} else if info.IsDir() {
		return "", fmt.Errorf("Tor executable is a directory: %s", absolute)
	}
	// The Expert Bundle layout is <root>/tor/tor[.exe] beside <root>/data.
	return filepath.Dir(filepath.Dir(absolute)), nil
}
