apply plugin: 'com.android.library'

group = 'br.com.ordinum.cialai.tunnel'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useDefaultAndroidSdkVersions()

android {
  namespace 'br.com.ordinum.cialai.tunnel'

  defaultConfig {
    minSdkVersion 26
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation files('libs/tunnelcore.aar')
}
